### PR TITLE
Update all packages

### PR DESCRIPTION
**Pull request by btd**
Hi there.

This PR is pretty optional, but good to have.
My main question, that i tried to solve is to enchace self exclusion for package contents. What i mean exactly: assume such modules injection:
```js
{
  Promise: 'pinkie-promise',
  fetch: 'unfetch'
}
```

There are several issues with this configuration:
1. Modules cannot import themselfs. So i would need to add something like this to exclude `[ './node_modules/pinkie-promise/**', './node_modules/unfetch/**']`.
2. Polyfills could depend from each other. In my example 'unfetch' depends from 'Promise' polyfill. In this case my exclusion would not allow to replace `Promise` usage in `unfetch` to use `pinkie-promise`.

Currently i solved this with something like this:
```js
const POLYFILLS = {
  Promise: 'pinkie-promise',
  fetch: 'unfetch'
};

const INJECTIONS = Object.entries(POLYFILLS).map(([nativeObj, packageName]) =>
  inject({
    exclude: `./node_modules/${packageName}/**`,
    [nativeObj]: packageName
  })
);

//and later

plugins: [
//...
...INJECTIONS,
//...
]
```

I have strong filling this plugin should do this itself. Am i right there? I tried to combine PR, but stucked at place where i need to check if `id` belongs to `packageName`. Any suggestions there?

### CODE REVIEW

**Comment by btd** [comment]
ping @collaborators @Rich-Harris

**Comment by btd** [comment]
Sorry for bothering @lukastaegert or @Rich-Harris can you please take a look. At least acorn update would be nice to have

**Comment by MattiasBuelens** [comment]
I need to pass a regex as `include` option, but this is only supported [since `rollup-pluginutils` 2.0.0](https://github.com/rollup/rollup-pluginutils/blob/master/CHANGELOG.md#200) whereas this plugin still uses 1.2.0.

I worked around this by forking the repo and then merging this PR myself, but I'd much prefer if this change landed in the "official" plugin. 😃

**Comment by lukastaegert** [comment]
Hi @btd, sorry this has been lying dormant for so long. The thing is that due to the very small core team developing rollup, smaller plugins tend to go under the radar easily.

I'll see what I can do.

Another question: Would you be interested in taking over responsibility for this plugin? I could give you the necessary access and publishing rights and you could improve it at your own discretion. I think this would be a win for all of us. Just tell me what you think.

**Comment by lukastaegert** [comment]
I updated the remaining dependencies and the build/ci scripts as well and published it as 2.1.0.

**Comment by btd** [comment]
@lukastaegert yes i am very interesting to taking over this plugin. We are using this plugin everyday.

**Comment by lukastaegert** [comment]
Cool, I sent you an invite! This will make you a rollup member and add you to the—newly created—rollup-plugin-inject "team" which *should* give you full admin access to this repo. You might want to confirm this by e.g. creating and pushing a branch to the repo.

If you tell me your npm handle, I can also give you the necessary publishing rights.

If you need help, a review for any of your work or have any questions, just ping me or use the "request review" feature.

**Pull request merged**
